0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,9 @@
 #!/usr/bin/env bash
 # script that transfers a file from our client to a server
 
-if [ $# -lt 4 ];
-than
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1;
+if [ $# -lt 4 ]; then
+    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
 path_to_file=$1
@@ -12,15 +11,14 @@ ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# disabbling strict host key checking
+# disabling strict host key checking
 
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
 
-# checking if the transfers was successful
-if [ $? -eq 0 ];
-than
-	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+# checking if the transfer was successful
+if [ $? -eq 0 ]; then
+    echo "FILE WAS TRANSFERRED SUCCESSFULLY"
 else
-	echo "FILE TRANSFERED FAILD"
+    echo "FILE TRANSFER FAILED"
 fi
